### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by Wuyida9** [lzeeorno/HBFormer-AFFSegNet#3]
Hi, am I training the model on 4090 right now, a round takes 20 minutes. Is this correct?
And I found I couldn't get any faster.
The result of your training is the result of running 900 rounds. Because I'm training too much now.
Look forward to your reply and thank you very much.

**Comment by lzeeorno** [comment]
> Hi, am I training the model on 4090 right now, a round takes 20 minutes. Is this correct? And I found I couldn't get any faster. The result of your training is the result of running 900 rounds. Because I'm training too much now. Look forward to your reply and thank you very much.

Yes, you are correct. I guess you are training the LiTS2017 dataset. The slow training speed is mainly due to two reasons. 1. In order to achieve higher accuracy, I did not use mixed precision training. 2. Because the data size of LiTs2017 is relatively large, it will be much faster if you train the Synapse dataset. If you want to increase the speed, you can try to increase the batch size. Or wait for me to open source the trained pth file later.
